import json
import os

from fastapi import APIRouter, HTTPException
from fastapi.responses import RedirectResponse
from pydantic import BaseModel, Field

from app.chain import answer_question, reset_conversation
from app.evaluation.judge import judge_faithfulness, judge_refusal, judge_relevance
from app.observability import log_request

router = APIRouter()


@router.get("/", include_in_schema=False)
def root() -> RedirectResponse:
    """Redirect bare host hits to the interactive Swagger UI."""
    return RedirectResponse(url="/docs")


class AskRequest(BaseModel):
    question: str = Field(..., min_length=1, max_length=2000)
    conversation_id: str | None = Field(
        default=None,
        description="Opaque ID — same value across turns enables multi-turn memory. Omit for single-turn.",
        max_length=128,
    )
    router_mode: str | None = Field(
        default=None,
        description="Override default router strategy: regex, embedding, llm, hybrid, or compare. "
                    "'compare' runs all three and returns the disagreement breakdown.",
    )
    decompose: bool = Field(
        default=False,
        description="When true, send the question to the Haiku decomposer first. Compound questions "
                    "get split into atomic sub-questions; each is routed/retrieved independently; "
                    "Sonnet synthesizes a unified answer. Atomic questions skip both extra calls.",
    )
    include_context: bool = Field(default=False, description="Include full retrieved context in response (debug).")


class Citation(BaseModel):
    type: str
    source: str | None = None
    page: int | None = None
    excerpt: str | None = None
    similarity: float | None = None
    query: str | None = None
    row_count: int | None = None
    id: str | None = None
    field: str | None = None
    error: str | None = None


class SqlInfo(BaseModel):
    query: str | None = None
    row_count: int | None = None
    tables: list[str] = []
    error: str | None = None


class Chunk(BaseModel):
    source: str
    page: int | None = None
    similarity: float
    content: str | None = None


class AskResponse(BaseModel):
    answer: str
    citations: list[Citation]
    query_type: str
    routing_reason: str
    router_mode: str | None = None
    router_comparison: dict | None = None
    conversation_id: str | None = None
    turn_index: int | None = None
    original_question: str | None = None
    routing_question: str | None = None
    reformulation_reason: str | None = None
    decomposition: dict | None = None
    sub_results: list[dict] | None = None
    latency_ms: float
    input_tokens: int | None = None
    output_tokens: int | None = None
    retrieved_sources: list[str] = []
    sql: SqlInfo | None = None
    chunks: list[Chunk] = []
    retrieved_context: str | None = None


@router.get("/health")
def health() -> dict:
    return {"status": "ok"}


@router.post("/ask", response_model=AskResponse)
def ask(req: AskRequest) -> AskResponse:
    if not req.question.strip():
        raise HTTPException(status_code=400, detail="Question cannot be empty.")
    result = answer_question(
        req.question,
        conversation_id=req.conversation_id,
        router_mode=req.router_mode,
        decompose=req.decompose,
    )
    log_request(req.question, result)

    if not req.include_context:
        result.pop("retrieved_context", None)
        result["chunks"] = [{**c, "content": None} for c in result.get("chunks", [])]

    return AskResponse(**result)


@router.delete("/conversations/{conversation_id}")
def clear_conversation(conversation_id: str) -> dict:
    """Drop the in-memory message history for a conversation."""
    reset_conversation(conversation_id)
    return {"status": "cleared", "conversation_id": conversation_id}


EVAL_RESULTS_PATH = "/app/eval_results.json"


@router.get("/evaluation/latest")
def get_latest_eval_results() -> dict:
    """Return the contents of the most recent eval_results.json.

    Generated by `scripts/evaluate.py` (invoke via `make evaluate` from the host).
    The file is bind-mounted so it survives container rebuilds.
    """
    if not os.path.exists(EVAL_RESULTS_PATH):
        raise HTTPException(
            status_code=404,
            detail="No eval results found. Run `make evaluate` from the host to generate them.",
        )
    try:
        with open(EVAL_RESULTS_PATH) as f:
            return json.load(f)
    except json.JSONDecodeError as exc:
        raise HTTPException(
            status_code=500,
            detail=f"eval_results.json is not valid JSON: {exc}",
        )


class JudgeRequest(BaseModel):
    question: str = Field(..., min_length=1, max_length=2000)
    answer: str = Field(..., min_length=1)
    context: str = ""
    metrics: list[str] = Field(
        default_factory=lambda: ["faithfulness", "answer_relevance"],
        description="Subset of: faithfulness, answer_relevance, refusal_correct",
    )


class JudgeResponse(BaseModel):
    faithfulness: dict | None = None
    answer_relevance: dict | None = None
    refusal_correct: dict | None = None


@router.post("/judge", response_model=JudgeResponse)
def judge(req: JudgeRequest) -> JudgeResponse:
    """Run LLM-as-judge metrics against an answer.

    Faithfulness and answer_relevance run for normal questions.
    refusal_correct is meant for OOS questions where the model should decline.
    """
    out: dict = {}
    if "faithfulness" in req.metrics:
        out["faithfulness"] = judge_faithfulness(req.answer, req.context)
    if "answer_relevance" in req.metrics:
        out["answer_relevance"] = judge_relevance(req.question, req.answer)
    if "refusal_correct" in req.metrics:
        out["refusal_correct"] = judge_refusal(req.question, req.answer)
    return JudgeResponse(**out)
